name: d3k0y
favicon: null
layout_spectrum: 0.6291553864721209
typography_spectrum: 0.5711417174898088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.552225302439183
  lightness: 0.7944793393835425
  saturation: 0.3966811839491129
  rhythmicContrast: 0.5263879462145269
purpose: []
